### ISSUE TITLE
Just askin

### ISSUE THREAD

**Issue by ErikPDev** [HyperFlareMC/KyllMe#1]
Hey there!
I'm Erik, I was wondering if I can use some of your code on a plugin  called AdvanceDeaths.
I'll give credits to you ofc.

Regards,
Erik
@HyperFlareMC

**Comment by HyperFlareMC** [comment]
Hey, @ErikPDev ! You're totally welcome to use some of this code in another plugin, credit is appreciated but not required as it's a GNU 3.0 License. If you have any issues, feel free to let me know. Have a good day :)
